config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

match "find_by_sql", :to => 'find_by_sql#index', via: [:get, :post]

app/controllers/find_by_sql_controller.rb
# -*- encoding: utf-8 -*-

class FindBySqlController < ApplicationController
  unloadable

  before_filter :require_admin

  def index
    @find_by_sql = FindBySqlHelper::FindBySql.new
    query = params[:find_by_sql][:query] if params.has_key?(:find_by_sql) && params[:find_by_sql].has_key?(:query)
    query ||= ""
    @find_by_sql.query = query

    @grid_option = true
    
    # select_all は insert や update も出来てしまうが、その後、内部での結果格納時に例外が出るので
    # トランザクションを脱出してrollbackできた
    begin
      ActiveRecord::Base.connection.transaction do
        @result = ActiveRecord::Base.connection.select_all(query) if query.present?
      end
    rescue ActiveRecord::ActiveRecordError => e
      flash.now[:error] = e.message
    ensure
      @result ||= []
    end
  end
end

app/helpers/find_by_sql_helper.rb
module FindBySqlHelper
  class FindBySql
    include ActiveModel::Model
    attr_accessor :query
  end
end

app/views/find_by_sql/index.html.erb
<%= javascript_include_tag "handsontable.full.min", :plugin=>"find_by_sql" %>
<%= stylesheet_link_tag "handsontable.full.min", :plugin=>"find_by_sql" %>
<%= javascript_include_tag "find_by_sql", :plugin=>"find_by_sql" %>

<h2><%=l(:label_find_by_sql)%></h2>

<%= labelled_form_for :find_by_sql, @find_by_sql, :url => find_by_sql_path do |f| %>

  <%= error_messages_for @find_by_sql %>

  <div class="box tabular">
    <p><%= f.text_area :query, :cols => 60, :rows => 5 %></p>
  </div>
  <%= f.submit l(:button_do) %>

<% end %>

<h2><%=l(:label_result)%></h2>

<% if @result.empty? %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
  <% if @grid_option %>
    <div class="box">
      <%= label_tag(:search, l(:label_search)) %>
      <%= text_field_tag "search[str]", "", :placeholder => l(:label_search_placeholder), :type => "search" %>
      <%= label_tag(:search_message, "", :id => :search_message) %>
    </div>
    <div id="grid" style="width: 90%" data-option="<%= @grid_option %>" data-data="<%= @result.to_json %>"></div>
  <% else %>
    <table class="list">
      <thead>
        <tr>
          <% @result.first.keys.each do |key| %>
            <th><%= key %></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @result.each do |rec| %>
          <tr class="<%= cycle('odd', 'even') %>">
            <% rec.values.each do |val| %>
              <td><%= val %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
<% end %>